/* 
    - write an object literal that stores information about your favorite movie. nameOfMovie, runTime, characters, and genre should be keys directly inside the object.
        - characters will be an array that should store no more than 2 character objects, each of which stores name, age, and items.
        - items itself will also be an array that should store no more than 2 item objects. These items objects can have key-value pairs of whatever you would like (ex. {itemOne: 'Bow and Arrow'}).

    - use console.log statements to show that you can print out the nameOfMovie, runTime, the characters, the name of a character, and one of the items a character has. Your console should look similar to the screenshot below.
*/

//NOTE: Write your code below and push back to your github branch.  SUBMIT YOUR GITHUB URL IN CANVAS
/*
let movie = [
    'Coming to America',
    '1h 57mim',
    cast[]
        Eddie Murphy: 
        age: 55,
        countryOfOrigin: 'USA',
        },
        
        {name: 'Arsenio Hall',
        age: 53,
        countryOfOrigin: 'USA',
        },
        {name: 'James Earl Jones',
        age: 75, 
        countryOfOrigin: 'USA',
        },
        {name: 'Shari Headley',
        age: 50,
        countryOfOrigin: 'USA'},
        {name: 'Madge Sinclair',
        age: 51,
        countryOfOrigin: 'USA',
        },
        {name: 'John Amos',
        age: 79,
        countryOfOrigin: 'USA',
        },
        {name: 'Paul Bates',
        age: 45,
        countryOfOrigin: 'USA',
        },
        {name: 'Vanessa Bell Calloway',
        age: 49,
        countryOfOrigin: 'USA',
        },
        {name: 'Allison Dean',
        age: 42,
        countryOfOrigin,}
    }, // end of cast array 
    chracters[
        {name: 'Prince Akeem',
        actor: 'Eddie Murphy',
        age: 25,
        countryOfOrigin: 'Zamunda'
        },
        {name: 'Clarence',
        actor: 'Eddie Murphy',
        age: 65, 
        countryOfOrigin: 'USA',
        },
        {name: 'Saul',
        actor: 'Eddie Murphy',
        age: 75, 
        countryOfOrigin: 'USA'
        },
        {name: 'Randy Watson',
        actor: 'Eddie Murphy',
        age: 28, 
        countryOfOrigin: 'USA',
        },
        {name: 'Semmi',
        actor: 'Arsenio Hall',
        age: 26,
        countryOfOrigin: 'Zamunda',
        },
        {name: 'Moris',
        actor: 'Arsenio Hall',
        age: 62,
        countryOfOrigin: 'USA',
        },
        {name: 'Extremlely Ugly Girl',
        actor: 'Aresenio Hall',
        age: 35,
        countryOfOrigin: 'USA',},
        {name: 'Rev. Brown',
        actor: 'Arsenio Hall',
        age: 69,
        countryOfOrigin: 'USA',
        },
        {name: 'King Jaffe Joffer',
        actor: 'James Earl Jones',
        age: 74,
        countryOfOrigin: 'Zamunda',
        },
        {name: 'Queen Aoleon',
        actor: 'Madge Sinclair', 
        age: 56,
        countryOfOrigin: 'Zamunda',
        },
        {name: 'Imani Izzi',
        actor: 'Vanessa Bell Calloway', 
        age: 22, 
        countryOfOrigin: 'Zamunda',
        },
        {name:'Cleo McDowell',
        actor: 'John Amos',
        age: 55,
        countryOfOrigin: 'USA',
        },
        {name: 'Lisa McDowell',
        actor: 'Shari Headley',
        age: 24,
        countryOfOrigin: 'USA',
        },
        {name: 'Patrice McDowell',
        actor: 'Allison Dean',
        age: 19,
        countryOfOrigin: 'USA',
        },
        {name: 'Oha',
        actor: 'Paul Bates',
        age: 20,
        }        
    ] // end of cast array
    */
]
